### ISSUE TITLE
ToDo: Inyección

### ISSUE THREAD

**Issue by FDSoftware** [FDSoftware/OpenEFI#12]
- [ ] Arranque en frio
 - [ ] Arranque en caliente
 - [ ] Void "Iny" para manejar algoritmos de inyeccion
 - [ ] Crear funcion para modificar el tiempo de inyeccion dependiendo de la carga del motor (ej: se acopla el compresor del A/A)

**Comment by FDSoftware** [comment]
chusmear luego para no mandarme cagada con los [algoritmos](https://www.forocepos.com/vbulletin/forum/foros-generales/potenciacion-y-mas/77036-c%C3%A1lculo-de-tiempo-de-inyecci%C3%B3n-y-de-angulo-de-encendido-ecumaster-ymods?93135-C%E1lculo-de-tiempo-de-inyecci%F3n-y-de-angulo-de-encendido-Ecumaster-Ymods=)
